### ISSUE TITLE
Could you pls provide me a code?

### ISSUE THREAD

**Issue by laputaqsh** [adityangud/Recommender_for_event_based_social_network#88]
Hi adityangud,

Sorry to trouble you. Because I can't download your code (maybe network or something else).

So, could you pls send the code to my email? My email address is: qsh115713@gmail.com.

Than you very much!

Best wishes for you.
laputaq

**Comment by navgupta14** [comment]
Hi laputaq,
Source code is open and publicly available along with the data and a demo video.
I didn't understand the problem faced by you.

Thanks
